### ISSUE TITLE
Product edit (category select)

### ISSUE THREAD

**Issue by michalpulpan** [ecoseller/ecoseller#113]
Modify Category select component in dashboard
* fetch category list (with nesting)
* Modify `<ProductCategorySelect>` so that it lists all categories with correct level indentation (children is more indented then it's parent)

You can begin by looking at `<DashboardProductsEditPage>` page (src/dashboard/pages/dashboard/catalog/products/edit/[id].tsx).

In `<ProductEditorWrapper>` is stored large state/reducer `productState` where all the fun begins. Because tha't s what stores all the data distributed into children.

This task is about modifying <ProductCategorySelect> component.

**Comment by michalpulpan** [comment]
@VL-CZ This is done, right?

**Comment by VL-CZ** [comment]
Yes
