### ISSUE TITLE
Product Variant model attrbutes

### ISSUE THREAD

**Issue by michalpulpan** [ecoseller/ecoseller#16]
Create Django models representing product attributes which will be attached to `ProductVariant` model so that some product can have for example `Color: red`,`Size: L` or `Memory: 512GB`. It's neccessary for `ProductVariant` to have multiple of those attributes and have them nicely/logicaly serialized and groupped.

**Comment by lakatop** [comment]
Pull request: https://github.com/ecoseller/ecoseller/pull/22
