### ISSUE TITLE
Category page - basic layout

### ISSUE THREAD

**Issue by lakatop** [ecoseller/ecoseller#36]
* filter box
* order by
* product listings
* pagination
* page title
* page description
* subcategories

Good inspirations:
* https://www.oveckarna.cz/obleceni/
* https://www.zoot.cz/katalog/17504/zeny
* ...

**Comment by michalpulpan** [comment]
![Image](https://user-images.githubusercontent.com/34132752/236137059-5de081c0-0c84-46a3-bfcb-ff0c203fef0d.png)
